# Generated by Django 5.2.4 on 2025-07-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('profesor', models.CharField(max_length=100)),
                ('aula', models.CharField(default='Aula 1', max_length=50)),
                ('credito', models.PositiveIntegerField(default=6)),
                ('horario', models.CharField(max_length=100)),
                ('cupo_maximo', models.PositiveIntegerField(default=10)),
            ],
        ),
    ]
